### ISSUE TITLE
questions about pasta and arm11, and mset

### ISSUE THREAD

**Issue by Syphurith** [nop90/PastaLaunch_MSET_4.X#1]
@nop90 I'm sorry to bother you... however i have some technical questions about the pasta.
You may already know that @felipejfc made some patches in ARM11, including [Eshop one](https://github.com/felipejfc/ygw-eshop-spoofer) and [Region Free](https://github.com/felipejfc/ygw-region-free). Since Braham own an ARM11 kernel before jumping to ARM9, I don't know if those patches can be done in braham's arm11 just before when it goes to CFW as supposed.

Also, about this mset version of pasta. I wonder if mset could support such patches (i don't mean the same offset and binary, surely).. and if you allow others to read the code and edit it, many thanks.
I only have a Old 4.5-JP console myself, _but still haven't tried out the cfw yet_ **Shame me** _cause i want to keep current FW version_. Might your work with mset be merge one day after?
_Well this one is based on assembly. much different from that one.._

**If get annoyed by this issue, please tell me to let me close it.** Please response, even a "I don't consider these things currently\* could be ok. Thanks. Best wishes. look forwards to your work.

**Comment by nop90** [comment]
Sorry to answering so late. I don't check too often github and the notification icon is so small!

IT should be possible to integrate Eshop spoof. For Region Free it doersent make sense because ir requires a boot that clean Pasta patches, so it's better to make a MSET launcher dedicated to the region Free alone. This is possible but I don't think I'll work on this.

For other info please write me on GBATemp. Thaks.

**Comment by Syphurith** [comment]
@nop90 So much thanks for your reply. The notification icon is quite small as it used to be.
I'm glad to hear that those eshop ones could be integrated in some means. No region free? well ok.
I think my question about this repo is solved totally, thanks, and i would close it.
